//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int option_id { get; set; }
        public string option_description { get; set; }
        public int poll_id { get; set; }
    
        public virtual Poll Poll { get; set; }
    }
}
