//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollAPI
{
    using System;
    using System.Collections.Generic;

    public partial class Poll
    {
        public int poll_id { get; set; }
        public string poll_description { get; set; }

        public virtual ICollection<string> options { get; set; }
        public virtual ICollection<string> Options {get;set;}
        public virtual Poll Poll1 { get; set; }
        public virtual Poll Poll2 { get; set; }
    }
}
