//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll
    {
        public int poll_id { get; set; }
        public string poll_description { get; set; }
    
        public virtual poll poll1 { get; set; }
        public virtual poll poll2 { get; set; }
        public virtual HashSet<string> options { get; set; }
    }
}
