//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote
    {
        public Nullable<System.DateTime> date { get; set; }
        public int option_id { get; set; }
    }
}
